#pragma once

#define STANDARD_WINDOW_W 1280
#define STANDARD_WINDOW_H 720

#define MAIN_SCREEN_W STANDARD_WINDOW_W*3
#define MAIN_SCREEN_H STANDARD_WINDOW_H

#define SECONDARY_SCREEN_W STANDARD_WINDOW_W
#define SECONDARY_SCREEN_H STANDARD_WINDOW_H

#define WEBCAM_W 320
#define WEBCAM_H 240

#define FPS 25

#define WAIT_FOR_SLEEP_MS 1000*60*20 // 20 minutes
#define SLEEP_THRESHOLD 0.05

#define AUDIO_NUM_OUT_CHANNELS  4
#define AUDIO_NUM_IN_CHANNELS   0
#define AUDIO_SAMPLE_RATE       44100
#define AUDIO_BUFFER_SIZE       256
#define AUDIO_NUM_BUFFER        4
